apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: java-quarkus-bdhokbce
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/java-quarkus-bdhokbce:f32695731fcb59c69cf396af69ce28adeb88879f@sha256:6ac7ac7c7786f62ba85e123f2ab74b9142bfdbf1391dc1ec498c6f6495d09329
          name: container-image
